### ISSUE TITLE
ok for SPX-WFG02 card

### ISSUE THREAD

**Issue by bucolo** [clsergent/hitachi_altwifi#1]
Bonjour
Merci beaucoup, grace a vous j'ai pu re-flasher ma première carte SPX-WFG02 .
Cette carte a en fait le même circuit imprimé que la votre .
j'avais acheté ces cartes dans mes 5 split Hitachi Takai (3 RAK-18QXE et 2 autres un peu plus puissant) a l’époque ou le wifi était en option...

Je fonctionnais actuellement avec l'integration aircloud et aussi en secours avec des modules esphome et heatpumpIR.
Ca fait plusieurs année que je cherche a intégrer mes split avec home assistant  1) en ayant un retour d'etat 2) en me passant d'Aircloud qui fonctionne aléatoirement...

j'attends des petites sondes à crochet pour pouvoir flasher plus rapidement mes 4 autres cartes
En attendant je vais pouvoir tester un peu plus.

j'ai utilisé Itchiptool gui pour flasher, j'ai eu plein d'erreur mais au final ça à fonctionné !

![Image](https://github.com/user-attachments/assets/752efb55-f3c2-476f-b1d8-9a76cf68f298)

Merci encore !

**Comment by bucolo** [comment]
Bonjour , finalement je pense avoir le même problème que vous. Ça fonctionne très bien au début puis après les commandes fonctionne mais je n'ai plus de retour d’état. je viens de retirer le logger pour voir...

**Comment by bucolo** [comment]
probleme du port serie corrigé avec : 
```
esphome:
  name: hitachi-ac
  friendly_name: hitachi-ac
  platformio_options:
    platform_packages:
      - framework-arduino-api @ https://github.com/hn/ArduinoCore-API#RingBufferFix
```
